name: Build Kernel

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          mkdir -p ~/workspace/source
          cd ~/workspace/source
          git clone https://github.com/realme-kernel-opensource/realmeGT_AndroidR-kernel-source kernel
          mkdir prebuild
          git clone https://android.googlesource.com/platform/prebuilts/build-tools
          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9

          echo "PATH=${{ github.workspace }}/workspace/source/prebuilts/clang/host/linux-x86/clang-r383902/bin:$PATH" >> $GITHUB_ENV

      - name: Export Environment Variables
        run: |
          echo "SOURCE_ROOT=~/workspace/source" >> $GITHUB_ENV
          echo "DEFCONFIG=lahaina_defconfig" >> $GITHUB_ENV
          echo "MAKE_PATH=~/workspace/source/prebuilts/build-tools/linux-x86/bin/" >> $GITHUB_ENV
          echo "CROSS_COMPILE=~/workspace/source/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-" >> $GITHUB_ENV
          echo "KERNEL_ARCH=arm64" >> $GITHUB_ENV
          echo "KERNEL_DIR=~/workspace/source/kernel/msm-5.4" >> $GITHUB_ENV
          echo "KERNEL_OUT=~/workspace/source/kernel/msm-5.4/../kernel_out" >> $GITHUB_ENV
          echo "KERNEL_SRC=~/workspace/source/kernel/msm-5.4/../kernel_out" >> $GITHUB_ENV
          echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "OUT_DIR=~/workspace/source/kernel/msm-5.4/../kernel_out" >> $GITHUB_ENV
          echo "ARCH=${{ env.KERNEL_ARCH }}" >> $GITHUB_ENV

      - name: Build Kernel Configuration
        run: |
          cd ~/workspace/source/kernel/msm-5.4
          make O=${{ env.OUT_DIR }} HOSTLDFLAGS="${{ env.TARGET_LINCLUDES }}" ARCH=${{ env.ARCH }} CROSS_COMPILE=${{ env.CROSS_COMPILE }} ${{ env.DEFCONFIG }}

      - name: Compile Kernel
        run: |
          cd ${{ env.OUT_DIR }}
          make ARCH=${{ env.ARCH }} CROSS_COMPILE=${{ env.CROSS_COMPILE }} O=${{ env.OUT_DIR }} ${{ env.TARGET_KERNEL_MAKE_ENV }}
